version: '3'

services: 
    todosDb:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todos
        ports:
            - "3306:3306"
    
    exo_python:
        build:
            context: ./exo_python
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - '5000:5000'